### ISSUE TITLE
Submodule installations on Windows

### ISSUE THREAD

**Issue by rogvidarge** [Teledyne-Marine/pyread7k#23]
# Issue
When used as a submodule, nested poetry installation, is quite difficult to get to work on windows. 

# Solution
Build the wheel using `poetry build` and then the package can be installed by pointing directly to the wheel instead of the submodule.

# Benefits
The wheel will allow easier installations of the package

**Comment by rogvidarge** [comment]
Yes, this is an issue when pyread7k is a git submodule of a python project that is configured using poetry. There are some hotfixes to poetry, but they require us to change some poetry specific functions, which could easily lead to the issue popping up again later. That's why I believe that the fix by building is the most future-proof and best solution.
W.r.t. whether it is us or users, the answer is either or. If we want the user to do it, we should just let them know in the README, that if they are using this on a windows machine, then if they are using poetry as a package manager, and pyread7k is a submodule, then they'll need to build the submodule repository code, and point the pyproject dependency to the wheel that is output from the build. Otherwise, we could build it as a Github Action, and then store it somewhere else so we don't check in the build artifacts.

**Comment by rasmus-klett-tele** [comment]
Is there anything in pyread7k specifically that causes this problem, or is it an issue with Poetry and any wheel-less package?

Since it is a quite niche problem, I'm leaning towards just documenting it. Expanding with infrastructure for storing wheels seems like it a hassle, and most users should install through the pypi package instead of git. Speaking of, we should probably release a new version soon..

**Comment by rogvidarge** [comment]
I agree. We could document our way out of it, and we should release a new version soon!
I can add a section to the README sometime next week. I'll also bump the version to 1.0.1 (I know updating the documentation isn't a "patch" but we've patched a number of things without bumping the version, so I think it is about time)

**Comment by rasmus-klett-tele** [comment]
We've done a number of breaking changes I think, so new version should be 2.0.0 I think. A commit to the README sounds good.

**Comment by rogvidarge** [comment]
Sure we can do that to. 2.0.0 it is. I'll assign myself to the task.

**Comment by rasmus-klett-tele** [comment]
Documented in [PR 25](https://github.com/Teledyne-Marine/pyread7k/pull/25)
