### ISSUE TITLE
Bad error message when record 7300 is missing

### ISSUE THREAD

**Issue by Zhaona715** [Teledyne-Marine/pyread7k#8]
I was trying to read a s7k file by  dataset = pyread7k.PingDataset(file_path)  but run into the following exception,  I also tried detection_example.py with my s7k file but still not working
However, I was able to open the s7k file successfully with  [7kRTT.exe](https://github.com/Teledyne-Marine/7k/blob/master/7kRTT/7kRTT.exe)   which means my s7k file is not broken

is anyone know how to fix this issue?

`Traceback (most recent call last):
  File "C:\Users\xxxx\PycharmProjects\reads7k\main.py", line 33, in <module>
    extactS7k(r"20140728_133637_SMB_Owen.s7k")
  File "C:\Users\xxxx\PycharmProjects\reads7k\main.py", line 21, in extactS7k
    dataset = pyread7k.PingDataset(file_path)
  File "C:\Users\xxxx\PycharmProjects\reads7k\venv\lib\site-packages\pyread7k\_ping.py", line 351, in __init__
    file_catalog = read_file_catalog(self.fhandle, file_header)
  File "C:\Usersxxxx\PycharmProjects\reads7k\venv\lib\site-packages\pyread7k\_utils.py", line 27, in read_file_catalog
    file_catalog: FileCatalog = _record(7300).read(source)
  File "C:\Users\xxxx\PycharmProjects\reads7k\venv\lib\site-packages\pyread7k\_datarecord.py", line 44, in read
    drf = self._block_drf.read(source)
  File "C:\Users\xxxx\PycharmProjects\reads7k\venv\lib\site-packages\pyread7k\_datablock.py", line 217, in read
    init_data = super().read(source)
  File "C:\Usersxxxx\PycharmProjects\reads7k\venv\lib\site-packages\pyread7k\_datablock.py", line 80, in read
    unpacked = self._struct.unpack(source.read(self.size))
struct.error: unpack requires a buffer of 64 bytes`

**Comment by rasmus-klett-tele** [comment]
Hi Zhaona. Does your file contain a correct 7200 and 7300 record? A valid 7k file should contain both, although some tools like 7kRTT may function without them. If it does contain those, I'm not sure what's wrong. In that case, could you send me the 7k file you are working with?

**Comment by rasmus-klett-tele** [comment]
I realized record 7300 is actually not required by the DFD, so your file is probably valid. However, this library currently requires that all 7k files do contain it, and as far as I know most Teledyne systems do produce it.

Do you have access to 7kFileMerge.exe or 7kFileRepair.exe? I believe those will add the required record. You may have them in the 'Utility' folder of your sonar software. I'm working on making them available online, and adding some documentation and error handling so this issue will be easier to handle in the future.

**Comment by Zhaona715** [comment]
Thank you for your prompt reply!
Yes, you are right, my s7k file doesn't contain 7300. I didn't use 7kFileMerge.exe or 7kFileRepair.exe before. Could you please let me know where can I find it?

**Comment by rasmus-klett-tele** [comment]
That's good :) There should probably be a custom error message for this case.
I have asked a colleague to make the tool available online, I will return to you when he does.

**Comment by rasmus-klett-tele** [comment]
Well, that was quick. It is now available over at [the 7k repo](https://github.com/Teledyne-Marine/7k/tree/master/7k%20Utilities).

Let me know if this solves your issue :) Out of curiosity, what are you planning to use this library for?

**Comment by Zhaona715** [comment]
So efficient! Thank you!
I am working on a project for the company's internal tool to extra some data from s7k file. :)

**Comment by rasmus-klett-tele** [comment]
Cool :) Well, I hope it works out for you. I'm gonna leave this issue open as a reminder to improve documentation and error message on this when I'm back from vacation.

**Comment by Zhaona715** [comment]
Just wondering do you have any plan to support s7k that doesn't contain 7300 in the future release?

**Comment by rasmus-klett-tele** [comment]
Yes, at some point I would like to implement a simple linear-reading of records, most of the current code should support that with no problem. Without the 7300 record, we lose the nice read-on-demand and random-access features, though.

Sorry for delayed response, I was on vacation.

**Comment by Zhaona715** [comment]
Yup, that makes sense to me.
Thanks!

**Comment by martimorta-at-work** [comment]
Hi @rasmus-klett-tele, I tried to use the Merge utility and the program crashes, from you reply in August:

> Yes, at some point I would like to implement a simple linear-reading of records, most of the current code should support that with no problem. Without the 7300 record, we lose the nice read-on-demand and random-access features, though.

If you started it somewhere I would be interested in giving it a try. Cheers!

**Comment by rasmus-klett-tele** [comment]
Hei @martimorta-at-work. Unfortunately I have not written the Merge utility, and I have not heard of other crashes, so I cannot help there.

Regarding a linear-reading mode, I'm unfortunately wrapped up in finalising another project right now, so I cannot spare time for it. I hope to get to it sometime in the spring. If you want to take a stab at it yourself, I would be happy to give you some pointers.

**Comment by rasmus-klett-tele** [comment]
Hi @martimorta-at-work  and @Zhaona715. We have just merged support for reading files without a catalog. You might be interested in checking out the master branch, and see if it works for you. If it doesn't, I would be very interested to see the 7k file that it fails on.
